export const data = [
  {
    id: 1,
    image:'./Hotels/hotel4.png',
    title: 'Taj Mahal Palace',
    location:'mumbai',
    description: '"True luxury is in the details. ',
    price :' 14000',
    Book_URL : '/hotels',
  },
  {
    id: 2,
    image:'./Hotels/hotel2.png',
    title: 'The Oberoi Grand',
    location:'Kolkata,WestBengal',
    description: 'Another good reason to stay that little bit longer.',
    price :'14000',
    Book_URL : '/hotel',
  },
  {
    id: 3,
    image:'./Hotels/hotel3.png',
    title: 'Umaid Bhawan Palace',
    location:'Jodhpur , Rajasthan',
    description: 'AN ARCHITECTURAL MARVEL',
    price :' 20000',
    Book_URL : '/hotel',
  },
  {
    id: 4,
    image:'./images/taj.jpg',
    title: 'Taj Mahal',
    location:'Agra,Uttar Pradesh',
    description: 'description. ',
    price :' 1000',
    Book_URL : '/hotel',
  },
  {
    id: 5,
    image:'./images/hero1.jpg',
    title: 'Oasis Resort',
    location:'Kerala',
    description: 'Coastal Serenity Awaits You ',
    price :' 15000',
    Book_URL : '/hotel',
  },
  {
    id: 6,
    image:'./images/hero2.jpg',
    title: 'Meadowview Lodge',
    location:'Goa',
    description: "Nature's Blissful Hideaway ",
    price :' 3000',
    Book_URL : '/hotel',
  },
  {
    id: 7,
    image:'./Hotels/hotel5.png',
    title: 'Whoopers Boutique',
    location:'kasol,Himachal Pradesh',
    description: `Nature's sanctuary, your peaceful retreat `,
    price :' 1200',
    Book_URL : '/hotel',
  },
]